name: Docs

on:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}.${{ github.sha }}.pages
  cancel-in-progress: true

jobs:
  pages:
    name: Build Sphinx Docs
    runs-on: [self-hosted, linux, x64, python, kubernetes]

    steps:
    - name: FS cleanup
      run: |
        rm -rf "$GITHUB_WORKSPACE"/*

    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install deps
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements.txt

    - name: Build docs
      run: |
        python -m sphinx -W -b html . _build/
