name: Publish

on:
  push:
    branches:
      - myInnerSourceBranch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools doxygen
        pip3 install --user -r Documentation/requirements.txt
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd Documentation
        make html
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html
        publish_branch: latestHTML
