name: Publish

on:
  push:
    branches:
      - myInnerSourceBranch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        pip3 install -U sphinx
        pip3 install sphinx-book-theme
        pip3 install myst-parser
        pip3 install sphinx-tabs
        pip3 install sphinx_design
        python -m sphinx -b html . _build/
        echo ${{ github.ref }}
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_build/html
        publish_branch: latestHTML

